#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301 status

# Update package repository and install nginx
apt-get -y update
apt-get -y install nginx

# Create a temporary configuration file for Nginx redirection
echo '
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Other server configurations can be added here if needed
}
' > /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site configuration
ln -sf /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
service nginx reload

