#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all the server's active IPv4 IPs

# Install Nginx if it's not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Ensure Nginx listens on port 80 for all IPv4 IPs
sudo sed -i 's/listen 80 default_server;/listen 0.0.0.0:80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart

